### ISSUE TITLE
block_comments2.java has some odd characters ending parsing.

### ISSUE THREAD

**Issue by jorconnor** [jorconnor/senior-design-rpl#18]
For Java block comments this bit of code 

	/**
	 * Compute insets. _______________________ |_________dx/2_________|
	 * |......|.´''''`.|......| |-dx/2-|| View ||-dx/2-|
	 * |______|`.____.´|______| |________ dx/2_________|
	 * 
	 * @param dx
	 *            the dx the horizontal unfilled space
	 * @param dy
	 *            the dy the horizontal unfilled space
	 */

Causes rosie to quit matching things. Might be an issue with accepted characters in rosie or might be a thing with java pattern?

**Comment by maya-shankar** [comment]
@jorconnor I don't see this block comment in block_comments2.java.

**Comment by maya-shankar** [comment]
Fixed / removed.
