### ISSUE TITLE
Handle multi-line statements in dependencies/general.

### ISSUE THREAD

**Issue by jorconnor** [jorconnor/senior-design-rpl#6]
Some languages like python allow multiline statements. For example the following are  equivalent and counted as a single statement:

import a, b, c
and
import a, b, \\
            c

**Comment by tgasda** [comment]
ew

**Comment by jorconnor** [comment]
Handling this isnt really feasible due to pythons nature at the moment... This hasnt been an issue for most other languages. Closing the issue as its simply a stale issue anyway.
